paths:
  static: static
  uploads: static/uploads
  layouts: layouts

timezone: Europe/London

_inputs:
  date:
    type: datetime
    instance_value: NOW
  publishdate:
    type: datetime
    instance_value: NOW
  description:
    type: textarea
    comment: Shown on the blog post and index pages. Plain text only.
  news_description:
    type: textarea
    comment: Shown in the Crunch web app's "What's new" notification panel (via RSS feed). Supports HTML. Typically a "click here to learn more" call-to-action style message.
  tags:
    type: array
    options:
      empty_type: string
  categories:
    type: array
    options:
      empty_type: string
  images:
    type: array
    options:
      empty_type: string

collections_config:
  features:
    path: content/dev/features
    icon: new_releases
    name: Feature Announcements
    parser: toml
    sort:
      key: date
      order: desc
    sort_options:
      - key: date
        order: desc
        label: Date (newest first)
    sortable: false
    subtext_key: description
    date_key: date
    filter:
      exclude:
        - _index.md
    _enabled_editors:
      - content
      - data
    add_options:
      - name: Add Feature
        schema: feature
    schemas:
      feature:
        path: .cloudcannon/schemas/feature.md
