paths:
  static: static
  uploads: static/uploads
  layouts: layouts

timezone: Europe/London

_inputs:
  tags:
    type: array
    options:
      empty_type: string
  categories:
    type: array
    options:
      empty_type: string
  images:
    type: array
    options:
      empty_type: string

collections_config:
  features:
    path: content/dev/features
    icon: new_releases
    name: Feature Announcements
    parser: toml
    _enabled_editors:
      - content
      - data
    add_options:
      - name: Add Feature
        schema: feature
    schemas:
      feature:
        path: .cloudcannon/schemas/feature.md
