baseURL = "//crunch.io/"

languageCode = "en-us"
title = "Online survey data analysis"
MetaDataFormat = "toml"
[pagination]
pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
description = "Prepare and analyze survey data quickly and easily."
product = "xtabs_intro.gif"
arrow = "arrow.png"
images = ["//crunch.io/img/logo-1200x630.png"]
search = true

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag = "tags"
